services:
  audio_miner:
    image: smilchsack/audio_miner:0.0.1
    container_name: audio_miner_collector
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /share/data/audio_mining:/app/audio_mining
      - /share/data/audio_mining/logs:/app/logs
    command: >
      start '[{"args":"--stream-url https://liveradio.swr.de/sw282p3/swr3/play.mp3 --sender swr3 --segment-time 3600 --base-dir /app/audio_mining --quality 128k --record-only --verbose"},
              {"args":"--stream-url https://wdr-wdr2-rheinruhr.icecastssl.wdr.de/wdr/wdr2/rheinruhr/mp3/128/stream.mp3 --sender wdr2 --segment-time 3600 --base-dir /app/audio_mining --quality 128k --record-only"},
              {"args":"--stream-url https://orf-live-oe3.mdn.ors.at/out/u/oe3/q4a/manifest.m3u8 --sender oe3 --segment-time 3600 --base-dir /app/audio_mining --quality 128k --record-only"},
              {"args":"--stream-url http://stream.srg-ssr.ch/m/drs3/mp3_128 --sender srf3 --segment-time 3600 --base-dir /app/audio_mining --quality 128k --record-only"}]'
    restart: unless-stopped