services:
  audio_miner:
    image: smilchsack/audio_miner:0.0.6
    container_name: audio_miner_collector
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /share/data/audio_mining:/app/audio_mining
      - /share/data/audio_mining/logs:/app/logs
    command: >
      start '[{"args":"--stream-url https://liveradio.swr.de/sw282p3/swr3/play.mp3 --sender swr3 --segment-time 300 --base-dir /app/audio_mining --record-only"},
              {"args":"--stream-url https://liveradio.swr.de/sw282p3/swr1rp/ --sender swr1 --segment-time 300 --base-dir /app/audio_mining --record-only"},
              {"args":"--stream-url https://wdr-wdr2-rheinruhr.icecastssl.wdr.de/wdr/wdr2/rheinruhr/mp3/128/stream.mp3 --sender wdr2 --segment-time 300 --base-dir /app/audio_mining --record-only"}]'
    restart: unless-stopped